name: CMake with Qt6 on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.7.2
  QT_BASE_DIR: C:/Qt
  QT_CMAKE_PATH: ${{ env.QT_BASE_DIR }}/Tools/CMake_6.7.2
  QT_DIR: ${{ env.QT_BASE_DIR }}/6.7.2/msvc2022_64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          arch: win64_msvc2022_64
          dir: ${{ env.QT_BASE_DIR }}

      - name: Configure CMake
        env:
          PATH: ${{ env.QT_CMAKE_PATH }}/bin;${{ env.PATH }}
        run: |
          cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DCMAKE_PREFIX_PATH=${{ env.QT_DIR }} `
            -DQt6_DIR=${{ env.QT_DIR }}/lib/cmake/Qt6

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }}
