name: CMake on Windows
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache OpenCASCADE
      id: cache-occt
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/../occt
        key: occt-7.9.1-windows

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/../Qt
        key: qt-6.8.3-windows-msvc2022

    - name: Check workspace and parent directory
      run: |
        echo "github.workspace: ${{ github.workspace }}"
        dir "${{ github.workspace }}"
        echo "Parent directory: ${{ github.workspace }}/.."
        dir "${{ github.workspace }}/.."
      shell: cmd

    - name: Download OpenCASCADE
      if: steps.cache-occt.outputs.cache-hit != 'true'
      run: |
        curl -L "https://github.com/Open-Cascade-SAS/OCCT/releases/download/V7_9_1/occt_vc14-64.zip" -o occt.zip
      shell: cmd

    - name: Extract OpenCASCADE
      if: steps.cache-occt.outputs.cache-hit != 'true'
      run: |
        mkdir "%GITHUB_WORKSPACE%\..\occt"
        tar -xf occt.zip -C "%GITHUB_WORKSPACE%\..\occt"
      shell: cmd

    - name: Verify Directory Structure
      run: |
        dir "%GITHUB_WORKSPACE%\.."
        dir "%GITHUB_WORKSPACE%\..\occt"
      shell: cmd
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        dir: ${{ github.workspace }}/..
        arch: 'win64_msvc2022_64'
        version: '6.8.3'  # 指定 Qt 版本为 6.8.3
      
    - name: Install Boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        boost_version: 1.81.0
        boost_install_dir: ${{ github.workspace }}/..
        platform_version: 2022
        toolset: msvc
    
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build ^
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
              -DOpenCASCADE_DIR="${{github.workspace}}/../occt/occt_vc14-64/cmake" ^
              -DQt6_DIR="${{github.workspace}}/../Qt/6.8.3/msvc2022_64/lib/cmake/Qt6" ^
              -DBOOST_ROOT="${{github.workspace}}/../boost" ^
              -DBOOST_NO_CMAKE=TRUE ^
              -DBOOST_NO_BOOST_CMAKE=TRUE
      shell: cmd

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel
      shell: cmd
      
